version: '3'

services:
  broker-service:
    build: ./../broker-service
    restart: always
    ports:
      - "8000:80"
    deploy:
      mode: replicated
      replicas: 1

  authentication-service:
    build: ./../authentication-service
    restart: always
    environment:
      DB_URL: "postgres://postgres:${POSTGRES_PASSWORD}@postgres:5432/authentication_service"
      API_USERNAME: ${API_USERNAME}
      API_PASSWORD: ${API_PASSWORD}
    deploy:
      mode: replicated
      replicas: 1

  sms-service:
    build:
      context: ./../sms-service
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      MOGODB_USERNAME: ${MOGODB_USERNAME}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}

  logger-service:
    build:
      context: ./../logger-service
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      MOGODB_USERNAME: ${MOGODB_USERNAME}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}

  postgres:
    image: 'postgres:14.2'
    ports:
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: authentication_service
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data

  mongo:
    image: 'mongo:latest'
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: sms-service
      MONGO_INITDB_ROOT_USERNAME: ${MOGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    volumes:
      - ./db-data/mongo/:/data/db
